### PR TITLE
fix license name

### PR DESCRIPTION
**Pull request by korobkov**
…to allow automatic license checks.

[skip ci]

### CODE REVIEW

**Comment by korobkov** [comment]
And please, release new gem version for this change to have effect…

**Comment by annaswims** [comment]
duplicate of #304

**Comment by annaswims** [comment]
it looks like what's currently in master is valid. [gemspec documentation](https://guides.rubygems.org/specification-reference/#licenses=)  

It seems to me that the issue is that "Ruby" is not one of the [most commonly used OSI approved licenses ](https://opensource.org/licenses/alphabetical)

**Comment by hsbt** [comment]
The current license name is valid with `Gem::Specification`.

**Pull request closed without merging**
