### PR TITLE
[DOC] RDoc for additions

### PR DESCRIPTION
**Pull request by BurdetteLamar**
I realized in working with BigDecimal here that the user is most like to pair the serialize/deserialize operations, so have written accordingly.

### CODE REVIEW

**Comment by BurdetteLamar** [comment]
Marking as draft while I do more additions doc.

**Comment by BurdetteLamar** [comment]
@hsbt, I don't think I caused these failed checks, but please correct me if I'm wrong.

**Comment by BurdetteLamar** [comment]
@hsbt, @nurse:  Will either of you be reviewing this?  If not, is there someone else I should ask?

**Comment by hsbt** [comment]
@BurdetteLamar  I exclude `truffleruby-head` from CI at https://github.com/flori/json/pull/551. You can resolve CI failure with `git rebase`.

**Comment by BurdetteLamar** [comment]
As I said earlier, I was not able to untangle this PR.  If no one objects, I'll close it and start fresh with a new PR;  there's no technical review so far, so I think nothing would be lost.

**Comment by BurdetteLamar** [comment]
Putting into new PR.

**Pull request closed without merging**
