### PR TITLE
[CI] setup supported JRubies to test against

### PR DESCRIPTION
**Pull request by kares**
... mostly to (current) supported JRubies

### CODE REVIEW

**Comment by kares** [comment]
CI should be all :green_heart: ... as https://github.com/flori/json/pull/361 gets in

**Comment by kares** [comment]
// cc @headius please review and ping @hsbt for merging

**Comment by marcandre** [comment]
Could you squash these commits please?

**Comment by marcandre** [comment]
Thanks, LGTM

**Pull request merged**
