### PR TITLE
Do not use BigDecimal.new to construct

### PR DESCRIPTION
**Pull request by headius**
Fixes jruby/jruby#7752

### CODE REVIEW

**Comment by hsbt** [comment]
@headius I fixed CI failure with https://github.com/flori/json/pull/544. Can you rebase this from HEAD?

**Comment by headius** [comment]
@hsbt Done!

**Comment by kares** [comment]
while this is :+1:, it's also breaking in terms of the `decimal_class` feature, which is an option `JSON` still supports.

**Comment by kares** [comment]
building on the changes here, I've come up with: https://github.com/flori/json/pull/546 ... which should be "more" :back:wards compatible

**Comment by hsbt** [comment]
@headius @kares I have no idea to merge this or #546.

**Comment by kares** [comment]
I would obviously vote for #546 but let's wait for @headius to do a review. 

The difference between the two is that this PR will not consider a user provided custom decimal_class option, while #546 will.

**Comment by headius** [comment]
#546 should be merged as it includes these fixes while presenting backward compatibility. Thanks @kares !

**Pull request closed without merging**
