### PR TITLE
[fix] Ruby 2.5 compat with JRuby 9.2

### PR DESCRIPTION
**Pull request by kares**
... also cleanup some pieces - mostly build tasks

wasn't possible to simply `rake test_ext`, now works

resolves GH-336

### CODE REVIEW

**Comment by kares** [comment]
@enebo arguably but there's the ugliness of Integer sub-class checking ... this seemed clearer
\+ also a hot-method so why not do a switch - and as 1.9.3 gets dropped this is pretty much official API

**Comment by kares** [comment]
... did have some more fixes (and performance improvement) e.g. BigDecimal isn't on par with C-code now, but someone needs to start merging

**Comment by headius** [comment]
The PR looks fine. I do not appear to have push rights for this repository, though.

@kares @enebo JRuby 1.7 is EOL...I don't think we should continue to try to support it in this gem. I'd also like to think 1.9.3 is EOL.

**Comment by kares** [comment]
@hsbt could you help us with our JRuby efforts for the json gem, or shall we ask someone else?
there's finally some activity on the repo (which is great), obviously you're busy fixing for C-Ruby.

**Comment by hsbt** [comment]
@kares I can handle this for JRuby compatibility on this repository. But I don't have a push grant of json gem on rubygems.org.

@flori Can you add me to owner grant of json gem?

**Comment by enebo** [comment]
@hsbt @headius does have push rights but I am unsure if he is in the position to give it to you or not.

**Comment by headius** [comment]
@kares I think we should do whatever's the best for 9k+ and ditch 1.7. The instanceof check would also be fine; there's only two subclasses of Integer in 2.5.

It would also be nice if you could move the non-bug-related commits to another PR. They're great, but they don't relate to this issue.

@hsbt We will ping you when we think this is ready to go. I have push rights for the gem, but you probably should get them too...

**Comment by headius** [comment]
@kares Actually I'd almost prefer to just use instanceof for all the types, putting the most common ones at the top (string, integer, array, hash, etc).

**Comment by kares** [comment]
> It would also be nice if you could move the non-bug-related commits to another PR. They're great, but they don't relate to this issue.

sorry about that - just ends up much more time spent on non-essential stuff for me. I'd like to have moved this forward and have more 'changes' around built on top - both fixes and refactorings (that I was hoping to get into whatever current stable is). did not see the other commits as harmful - they actually establish-ed a usable base line for me. if I made things hard to merge, I am sorry and will move them around.

> I think we should do whatever's the best for 9k+ and ditch 1.7.

once again I did not want to force breaking change for the 2.1 line, which I hoped this would end up at.

> The instanceof check would also be fine; there's only two subclasses of Integer in 2.5.

... is this the 'actual' thing blocking the merge here?

**Comment by wezm** [comment]
Hi folks, is there anything I can do to help get this merged? It looks like @kares addressed the feedback. It would would be great to see this make it into a JRuby release so we can upgrade our app from 9.1 to 9.2.

**Comment by headius** [comment]
@wezm There has not been a new release of this gem in two years, unfortunately, and I don't know how to make that happen. I have push rights for the gem, but I do not have push rights for this repository.

I would hate to have to fork the repository so we can get fixes out, but this is getting kind of ridiculous.

**Comment by kares** [comment]
@skarmakar that is exactly what we're fixing here (a 9.2 issue)
just to be clear as the above comment might confuse folks :disappointed: 
9.2 without the patch (using json 2.1.0)
```
$ jruby -v -rjson -e 'p({"a" => 1, "b" => 12345678901234567890}.to_json)'
jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 Java HotSpot(TM) 64-Bit Server VM 25.171-b11 on 1.8.0_171-b11 +jit [linux-x86_64]
Unhandled Java exception: java.lang.ClassCastException: org.jruby.RubyBignum cannot be cast to org.jruby.RubyFixnum
java.lang.ClassCastException: org.jruby.RubyBignum cannot be cast to org.jruby.RubyFixnum
              generate at json/ext/Generator.java:224
                 visit at json/ext/Generator.java:354
                 visit at org/jruby/RubyHash.java:668
          visitLimited at org/jruby/RubyHash.java:690
              visitAll at org/jruby/RubyHash.java:2725
              generate at json/ext/Generator.java:333
              generate at json/ext/Generator.java:306
           generateNew at json/ext/Generator.java:171
          generateJson at json/ext/Generator.java:35
               to_json at json/ext/GeneratorMethods.java:70
                  call at json/ext/GeneratorMethods$RbHash$INVOKER$s$0$0$to_json.gen:-1
                  call at org/jruby/internal/runtime/methods/JavaMethod.java:793
                  call at org/jruby/internal/runtime/methods/DynamicMethod.java:191
          cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:325
                  call at org/jruby/runtime/callsite/CachingCallSite.java:141
  invokeOther3:to_json at -e:1
                <main> at -e:1
   invokeWithArguments at java/lang/invoke/MethodHandle.java:627
                  load at org/jruby/ir/Compiler.java:94
             runScript at org/jruby/Ruby.java:849
           runNormally at org/jruby/Ruby.java:772
           runNormally at org/jruby/Ruby.java:790
           runFromMain at org/jruby/Ruby.java:602
         doRunFromMain at org/jruby/Main.java:415
           internalRun at org/jruby/Main.java:307
                   run at org/jruby/Main.java:234
                  main at org/jruby/Main.java:206
```
9.2 with changes from the PR : 
```
$ jruby -v -Ilib -rjson -e 'p({"a" => 1, "b" => 12345678901234567890}.to_json)'
jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 Java HotSpot(TM) 64-Bit Server VM 25.171-b11 on 1.8.0_171-b11 +jit [linux-x86_64]
"{\"a\":1,\"b\":12345678901234567890}"
```

9.1.17 works fine with (also without) the patch : 
```
$ jruby -v -Ilib -rjson -e 'p({"a" => 1, "b" => 12345678901234567890}.to_json); p JSON::VERSION'
jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 Java HotSpot(TM) 64-Bit Server VM 25.171-b11 on 1.8.0_171-b11 +jit [linux-x86_64]
"{\"a\":1,\"b\":12345678901234567890}"
"2.1.0"
```

**Comment by skarmakar** [comment]
@kares I am really sorry if it caused any confusion. Definitely want this fix to work and solve the issue.

I used this branch in a rails project, but still was getting this same error. Is it something that even if we mention a different `json` gem in the Gemfile, still jruby loads the default json gem? I have created a [sample app](https://github.com/skarmakar/json_debug) for reference. Please let me know if I am missing something.

**Comment by kares** [comment]
seems @flori [landed the patch](https://github.com/flori/json/commit/81fbce0aa66738b3ea9758db2aee44b80bb8f9a5) from this PR on master (for json 2.2.0).

so we have JRuby progress, still not on par with the C code (BigDecimal warning) hopefully to happen later

**Comment by headius** [comment]
I have updated JRuby 9.2.7 to json 2.2.0.

**Comment by skarmakar** [comment]
@kares @headius I confirm that it works with JRuby 9.2.5 by forcefully upgrading json to 2.2.0. Going to try 9.2.7

**Pull request closed without merging**
