### PR TITLE
add metadata for rubygems.org

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by noraj** [comment]
also can close #378

**Comment by noraj** [comment]
PS : I don't know why github is seeing the file as binary now: 
image

**Comment by hsbt** [comment]
@noraj Can you rebase from the current master branch? I removed control-chars from json.gemspec at https://github.com/flori/json/pull/398

**Comment by noraj** [comment]
@hsbt pushed

**Comment by hsbt** [comment]
Thanks!

**Pull request merged**
