### PR TITLE
Remove useless `stub` headers from .gemspec.

### PR DESCRIPTION
**Pull request by voxik**
The headers are generated by RubyGems in an installed .gemspec file but have no meaning in the source .gemspec file.

### CODE REVIEW

**Comment by hsbt** [comment]
@voxik I removed control-chars at https://github.com/flori/json/pull/398 . Can you rebase this from the current master branch? Thanks.

**Comment by hsbt** [comment]
@voxik ping

**Comment by marcandre** [comment]
This should be closed at it is not the correct solution. I propose #415 instead.

**Comment by hsbt** [comment]
make sense. Thanks.

**Pull request closed without merging**
